import './globals.css';

import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import { ReactNode } from 'react';

import { cn } from '@/lib/utils';

const poppins = Poppins({
  subsets: ['latin'],
  variable: '--font-sans',
  weight: ['400', '600'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={cn(
          'bg-background flex min-h-screen justify-center font-sans antialiased',
          poppins.variable,
        )}
      >
        <div className="h-full w-full max-w-5xl px-4">{children}</div>
      </body>
    </html>
  );
}
